version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
hooks:
  BeforeInstall:
    - location: script/install.sh
      timeout: 100
      runas: DeployTest
  AfterInstall:
    - location: script/change_permissions.sh
      timeout: 100
      runas: DeployTest
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      runas: DeployTest
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 100
      runas: DeployTest
